### PR TITLE
Refresh token and S2S auth

### PR DESCRIPTION
**Pull request by mark-data8**
Adds options to authenticate connections using OAuth refresh tokens and S2S authentication.

We gather these authentication details for a multi-tenant application, and on occasion it would be very helpful to be able to use them with XrmToolBox plugins. Because these connection details are gathered externally there is no UI for entering them into the connection wizard, they would need to be entered directly into the connection list XML.

I think this should also address issue #74

### CODE REVIEW

**Comment by MscrmTools** [comment]
I guess I would like to have a UI to provide these information, instead of putting eveything in XML only.

And it seems that CrmServiceClient support connecting using S2S according to [this blog article](https://dynamicsforcrm.wordpress.com/2018/07/16/server-to-server-authentication-using-crmserviceclient/). It maybe be a simpler way to handle these kind of connection, isn't it?

**Comment by mark-data8** [comment]
Thanks for the feedback! I've pushed some more changes that uses the `CrmServiceClient.AuthOverrideHook` property to do the authentication.

I haven't added a UI yet - I don't want to make the process of adding a new connection more complicated for the standard use case by adding in a bunch of extra options that I guess would look pretty confusing. I can have a play around to see if I can come up with something that looks acceptable.

**Comment by mark-data8** [comment]
I've just been working on extending the existing Oauth connection control for the connection wizard, will push some more changes shortly

**Comment by mark-data8** [comment]
I've added this into the connection wizard now as follows:

1. Relabelled the "Use Multi Factor Authentication" checkbox to be "Use Multi Factor Auth, OAuth or S2S":
image

2. On the OAuth settings screen, added text boxes for Client Secret and Refresh Token:
image

3. If a client secret is entered, clicking Next bypasses the username & password entry screen and proceeds directly to checking the connection.

**Comment by MscrmTools** [comment]
That looks good!
Thanks! Is that already submitted or should I wait you update the PR to pull it?

**Comment by mark-data8** [comment]
That's all in the latest commits

**Comment by MscrmTools** [comment]
Ok, I merge it!

Thanks

**Comment by MscrmTools** [comment]
@mark-data8, I review the changes you made. 
Juste one question : it seems to me that Refresh Token has no value to be displayed in the UI. You don't know what it is and it is just populated after the connection is established. Am I right?

**Comment by mark-data8** [comment]
Correct - we have a web application that starts the OAuth process and stores the refresh token in a database. It's not a value that a regular user would ever see.

**Comment by MscrmTools** [comment]
Ok, I will remove this control from the UI then

**Pull request merged**
