### PR TITLE
Connection method for `Service principal` implemented. 

### PR DESCRIPTION
**Pull request by imranakram**
Recently our organization has completely enforced MFA which resulted in some pretty severe consequences like not even being able to login via App Password in the connection string. So we've setup a Service Principal and Azure and mapped it to an Application User in CRM. Then we're able to authenticate via Azure AppId, client secret and the Uri. I saw the oAuth implementation by @mark-data8 which seems very close to what is needed except how it makes up the Url with server name and port so I added another control and made a separate implementation just to be safe since this is my first pull request on this project. This adds a new property `UseServicePrincipal` and I have removed the reference to `ConnectOAuth` method in this since it was only checking the presence of client secret which is used here as well. Sorry about that Mark. 

Please have a review.

### CODE REVIEW

**Comment by MscrmTools** [comment]
Thank you for that PR 
I will review it but I’m in the process of revamping the whole connection code.
Could you test your implementation on the branch Certificate-connection? I added more than just certificate connection in there and it will certainly become the base code really soon

**Comment by MscrmTools** [comment]
Also wondering... is user service principle not the same thing than connecting with a clientid and secret?

**Comment by MscrmTools** [comment]
Reviewing your code. It seems that it’s like client id and secret and I implemented that in the certificate-connection branch. Can you test it to check if it works for you?

**Comment by imranakram** [comment]
Thanks, I've tried to run the certificate-connection branch and it seems client Id & secret would be applicable. At the moment I got this after I supplied the client Id and secret. Must be a bug in there. Will try and go through in more detail later on 
image

**Comment by imranakram** [comment]
Just got past this after a minor change, but getting
image

I've seen a similar message while working on this PR, apparently the encryption doesn't work.

**Comment by MscrmTools** [comment]
Yes, I guess I have issue with decrypting for now in this branch. What if you test by creating the connection from this branch (which does not implies encrypting/decrypting yet)? I guess it should work

**Comment by MarkMpn** [comment]
I'm all in favour of any consolidation of connection methods rather than adding more. I'm more than happy for my existing implementations to be removed in favour of any replacement provided that I can still connect using any of three common authentication methods we use:

1. Username & password
2. App user (ClientId, ClientSecret, RedirectUrl)
3. OAuth refresh token (RefreshToken, RedirectUrl)

If there's ongoing work to refactor this I'd be happy to test/contribute to make sure it covers all our use cases.

**Comment by MscrmTools** [comment]
Sure! Please use the certificate-connection branch.
I fixed the client secret not being decrypted before usage.

**Comment by MscrmTools** [comment]
Branch updated with minor improvements and way to ask for user password if needed

**Comment by MscrmTools** [comment]
@imranakram, I will close the PR without merging because of too much changed on the certificate-connection branch. 
Can you test if this branch fits your need? if not, please provide a PR for this branch

**Pull request closed without merging**
