### PR TITLE
Fix for connection wizard log in

### PR DESCRIPTION
**Pull request by Klind23**

### CODE REVIEW

**Comment by rappen** [comment]
🙇

**Comment by Klind23** [comment]
> 🙇

My emoji game is not that strong.Is there any issue with the PR?

**Comment by rappen** [comment]
Sorry - no issue, I am bowing in gratitude to a long awaited improvement 😊

**Comment by Klind23** [comment]
> Sorry - no issue, I am bowing in gratitude to a long awaited improvement 😊
> I always forget to uncheck that box, and always get an error...

Oh okay,thank you very much 😀

**Pull request merged**
